-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [btree_kernel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace btree_kernel

/-- [btree_kernel::T]
    Source: 'src/lib.rs', lines 21:0-21:24
    Visibility: public -/
@[global_simps, irreducible] def T : Std.Usize := 32#usize

/-- [btree_kernel::MAX_KEYS]
    Source: 'src/lib.rs', lines 22:0-22:38
    Visibility: public -/
@[global_simps, irreducible]
def MAX_KEYS : Result Std.Usize := do let i ← 2#usize * T
                                      i - 1#usize

mutual

/-- [btree_kernel::Children]
    Source: 'src/lib.rs', lines 24:0-27:1
    Visibility: public -/
@[discriminant isize]
inductive Children where
| Nil : Children
| Cons : Node → Children → Children

/-- [btree_kernel::Node]
    Source: 'src/lib.rs', lines 29:0-34:1
    Visibility: public -/
inductive Node where
| mk : alloc.vec.Vec (Std.U64 × Std.U64) → Children → Node

end

def Node.entries (x : Node) := match x with | Node.mk x1 _ => x1

def Node.children (x : Node) := match x with | Node.mk _ x1 => x1

@[simp]
theorem Node.entries._simpLemma_ (entries : alloc.vec.Vec (Std.U64 × Std.U64))
  (children : Children) : (Node.mk entries children).entries = entries :=
  by rfl

@[simp]
theorem Node.children._simpLemma_ (entries : alloc.vec.Vec (Std.U64 ×
  Std.U64)) (children : Children) :
  (Node.mk entries children).children = children := by rfl

/-- [btree_kernel::BTree]
    Source: 'src/lib.rs', lines 36:0-39:1
    Visibility: public -/
structure BTree where
  root : Node
  len : Std.Usize

/-- [btree_kernel::InsertResult]
    Source: 'src/lib.rs', lines 41:0-49:1
    Visibility: public -/
@[discriminant isize]
inductive InsertResult where
| Fit : Node → Bool → InsertResult
| Split : Node → (Std.U64 × Std.U64) → Node → Bool → InsertResult

/-- [btree_kernel::find_pos]: loop body 0:
    Source: 'src/lib.rs', lines 1:0-74:5 -/
@[rust_loop_body]
def find_pos_loop.body
  (entries : alloc.vec.Vec (Std.U64 × Std.U64)) (key : Std.U64)
  (lo : Std.Usize) (hi : Std.Usize) (found : Bool) (pos : Std.Usize) :
  Result (ControlFlow (Std.Usize × Std.Usize × Bool × Std.Usize) (Std.Usize
    × Bool × Std.Usize))
  := do
  if lo < hi
  then
    if found
    then ok (done (lo, true, pos))
    else
      let i ← hi - lo
      let i1 ← i / 2#usize
      let mid ← lo + i1
      let (k, _) ←
        alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Std.U64 ×
          Std.U64)) entries mid
      if k = key
      then ok (cont (lo, hi, true, mid))
      else
        if k < key
        then let lo1 ← mid + 1#usize
             ok (cont (lo1, hi, false, pos))
        else ok (cont (lo, mid, false, pos))
  else ok (done (lo, found, pos))

/-- [btree_kernel::find_pos]: loop 0:
    Source: 'src/lib.rs', lines 1:0-74:5 -/
@[rust_loop]
def find_pos_loop
  (entries : alloc.vec.Vec (Std.U64 × Std.U64)) (key : Std.U64)
  (lo : Std.Usize) (hi : Std.Usize) (found : Bool) (pos : Std.Usize) :
  Result (Std.Usize × Bool × Std.Usize)
  := do
  loop
    (fun (lo1, hi1, found1, pos1) => find_pos_loop.body entries key lo1 hi1
      found1 pos1)
    (lo, hi, found, pos)

/-- [btree_kernel::find_pos]:
    Source: 'src/lib.rs', lines 58:0-80:1 -/
def find_pos
  (entries : alloc.vec.Vec (Std.U64 × Std.U64)) (key : Std.U64) :
  Result (Bool × Std.Usize)
  := do
  let hi := alloc.vec.Vec.len entries
  let (lo, found, pos) ← find_pos_loop entries key 0#usize hi false 0#usize
  if found
  then ok (true, pos)
  else ok (false, lo)

/-- [btree_kernel::insert_entry_at]: loop body 0:
    Source: 'src/lib.rs', lines 86:4-89:5 -/
@[rust_loop_body]
def insert_entry_at_loop0.body
  (v : alloc.vec.Vec (Std.U64 × Std.U64)) (pos : Std.Usize)
  (out : alloc.vec.Vec (Std.U64 × Std.U64)) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec (Std.U64 × Std.U64)) × Std.Usize)
    ((alloc.vec.Vec (Std.U64 × Std.U64)) × Std.Usize))
  := do
  if i < pos
  then
    let p ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Std.U64 ×
        Std.U64)) v i
    let out1 ← alloc.vec.Vec.push out p
    let i1 ← i + 1#usize
    ok (cont (out1, i1))
  else ok (done (out, i))

/-- [btree_kernel::insert_entry_at]: loop 0:
    Source: 'src/lib.rs', lines 86:4-89:5 -/
@[rust_loop]
def insert_entry_at_loop0
  (v : alloc.vec.Vec (Std.U64 × Std.U64)) (pos : Std.Usize)
  (out : alloc.vec.Vec (Std.U64 × Std.U64)) (i : Std.Usize) :
  Result ((alloc.vec.Vec (Std.U64 × Std.U64)) × Std.Usize)
  := do
  loop
    (fun (out1, i1) => insert_entry_at_loop0.body v pos out1 i1)
    (out, i)

/-- [btree_kernel::insert_entry_at]: loop body 1:
    Source: 'src/lib.rs', lines 91:4-94:5 -/
@[rust_loop_body]
def insert_entry_at_loop1.body
  (v : alloc.vec.Vec (Std.U64 × Std.U64))
  (out : alloc.vec.Vec (Std.U64 × Std.U64)) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec (Std.U64 × Std.U64)) × Std.Usize)
    (alloc.vec.Vec (Std.U64 × Std.U64)))
  := do
  let i1 := alloc.vec.Vec.len v
  if i < i1
  then
    let p ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Std.U64 ×
        Std.U64)) v i
    let out1 ← alloc.vec.Vec.push out p
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [btree_kernel::insert_entry_at]: loop 1:
    Source: 'src/lib.rs', lines 91:4-94:5 -/
@[rust_loop]
def insert_entry_at_loop1
  (v : alloc.vec.Vec (Std.U64 × Std.U64))
  (out : alloc.vec.Vec (Std.U64 × Std.U64)) (i : Std.Usize) :
  Result (alloc.vec.Vec (Std.U64 × Std.U64))
  := do
  loop
    (fun (out1, i1) => insert_entry_at_loop1.body v out1 i1)
    (out, i)

/-- [btree_kernel::insert_entry_at]:
    Source: 'src/lib.rs', lines 83:0-96:1 -/
def insert_entry_at
  (v : alloc.vec.Vec (Std.U64 × Std.U64)) (pos : Std.Usize)
  (x : (Std.U64 × Std.U64)) :
  Result (alloc.vec.Vec (Std.U64 × Std.U64))
  := do
  let (out, i) ←
    insert_entry_at_loop0 v pos (alloc.vec.Vec.new (Std.U64 × Std.U64))
      0#usize
  let out1 ← alloc.vec.Vec.push out x
  insert_entry_at_loop1 v out1 i

/-- [btree_kernel::replace_entry]: loop body 0:
    Source: 'src/lib.rs', lines 102:4-109:5 -/
@[rust_loop_body]
def replace_entry_loop.body
  (v : alloc.vec.Vec (Std.U64 × Std.U64)) (pos : Std.Usize)
  (x : (Std.U64 × Std.U64)) (out : alloc.vec.Vec (Std.U64 × Std.U64))
  (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec (Std.U64 × Std.U64)) × Std.Usize)
    (alloc.vec.Vec (Std.U64 × Std.U64)))
  := do
  let i1 := alloc.vec.Vec.len v
  if i < i1
  then
    let out1 ←
      if i = pos
      then alloc.vec.Vec.push out x
      else
        do
        let p ←
          alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Std.U64
            × Std.U64)) v i
        alloc.vec.Vec.push out p
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [btree_kernel::replace_entry]: loop 0:
    Source: 'src/lib.rs', lines 102:4-109:5 -/
@[rust_loop]
def replace_entry_loop
  (v : alloc.vec.Vec (Std.U64 × Std.U64)) (pos : Std.Usize)
  (x : (Std.U64 × Std.U64)) (out : alloc.vec.Vec (Std.U64 × Std.U64))
  (i : Std.Usize) :
  Result (alloc.vec.Vec (Std.U64 × Std.U64))
  := do
  loop
    (fun (out1, i1) => replace_entry_loop.body v pos x out1 i1)
    (out, i)

/-- [btree_kernel::replace_entry]:
    Source: 'src/lib.rs', lines 99:0-111:1 -/
@[reducible]
def replace_entry
  (v : alloc.vec.Vec (Std.U64 × Std.U64)) (pos : Std.Usize)
  (x : (Std.U64 × Std.U64)) :
  Result (alloc.vec.Vec (Std.U64 × Std.U64))
  := do
  replace_entry_loop v pos x (alloc.vec.Vec.new (Std.U64 × Std.U64)) 0#usize

/-- [btree_kernel::entries_prefix]: loop body 0:
    Source: 'src/lib.rs', lines 117:4-120:5 -/
@[rust_loop_body]
def entries_prefix_loop.body
  (v : alloc.vec.Vec (Std.U64 × Std.U64)) (n : Std.Usize)
  (out : alloc.vec.Vec (Std.U64 × Std.U64)) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec (Std.U64 × Std.U64)) × Std.Usize)
    (alloc.vec.Vec (Std.U64 × Std.U64)))
  := do
  if i < n
  then
    let p ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Std.U64 ×
        Std.U64)) v i
    let out1 ← alloc.vec.Vec.push out p
    let i1 ← i + 1#usize
    ok (cont (out1, i1))
  else ok (done out)

/-- [btree_kernel::entries_prefix]: loop 0:
    Source: 'src/lib.rs', lines 117:4-120:5 -/
@[rust_loop]
def entries_prefix_loop
  (v : alloc.vec.Vec (Std.U64 × Std.U64)) (n : Std.Usize)
  (out : alloc.vec.Vec (Std.U64 × Std.U64)) (i : Std.Usize) :
  Result (alloc.vec.Vec (Std.U64 × Std.U64))
  := do
  loop
    (fun (out1, i1) => entries_prefix_loop.body v n out1 i1)
    (out, i)

/-- [btree_kernel::entries_prefix]:
    Source: 'src/lib.rs', lines 114:0-122:1 -/
@[reducible]
def entries_prefix
  (v : alloc.vec.Vec (Std.U64 × Std.U64)) (n : Std.Usize) :
  Result (alloc.vec.Vec (Std.U64 × Std.U64))
  := do
  entries_prefix_loop v n (alloc.vec.Vec.new (Std.U64 × Std.U64)) 0#usize

/-- [btree_kernel::entries_suffix]: loop body 0:
    Source: 'src/lib.rs', lines 128:4-131:5 -/
@[rust_loop_body]
def entries_suffix_loop.body
  (v : alloc.vec.Vec (Std.U64 × Std.U64))
  (out : alloc.vec.Vec (Std.U64 × Std.U64)) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec (Std.U64 × Std.U64)) × Std.Usize)
    (alloc.vec.Vec (Std.U64 × Std.U64)))
  := do
  let i1 := alloc.vec.Vec.len v
  if i < i1
  then
    let p ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Std.U64 ×
        Std.U64)) v i
    let out1 ← alloc.vec.Vec.push out p
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [btree_kernel::entries_suffix]: loop 0:
    Source: 'src/lib.rs', lines 128:4-131:5 -/
@[rust_loop]
def entries_suffix_loop
  (v : alloc.vec.Vec (Std.U64 × Std.U64))
  (out : alloc.vec.Vec (Std.U64 × Std.U64)) (i : Std.Usize) :
  Result (alloc.vec.Vec (Std.U64 × Std.U64))
  := do
  loop
    (fun (out1, i1) => entries_suffix_loop.body v out1 i1)
    (out, i)

/-- [btree_kernel::entries_suffix]:
    Source: 'src/lib.rs', lines 125:0-133:1 -/
@[reducible]
def entries_suffix
  (v : alloc.vec.Vec (Std.U64 × Std.U64)) (n : Std.Usize) :
  Result (alloc.vec.Vec (Std.U64 × Std.U64))
  := do
  entries_suffix_loop v (alloc.vec.Vec.new (Std.U64 × Std.U64)) n

mutual

/-- [btree_kernel::clone_node]:
    Source: 'src/lib.rs', lines 142:0-147:1
    Visibility: public -/
def clone_node (n : Node) : Result Node := do
  let v ←
    alloc.vec.CloneVec.clone (BuiltinClone (Std.U64 × Std.U64)) n.entries
  let c ← clone_children n.children
  ok (Node.mk v c)
partial_fixpoint

/-- [btree_kernel::clone_children]:
    Source: 'src/lib.rs', lines 150:0-157:1
    Visibility: public -/
def clone_children (c : Children) : Result Children := do
  match c with
  | Children.Nil => ok Children.Nil
  | Children.Cons n rest =>
    let n1 ← clone_node n
    let c1 ← clone_children rest
    ok (Children.Cons n1 c1)
partial_fixpoint

end

/-- [btree_kernel::children_len]:
    Source: 'src/lib.rs', lines 160:0-165:1
    Visibility: public -/
def children_len (c : Children) : Result Std.Usize := do
  match c with
  | Children.Nil => ok 0#usize
  | Children.Cons _ rest => let i ← children_len rest
                            1#usize + i
partial_fixpoint

/-- [btree_kernel::child_at]:
    Source: 'src/lib.rs', lines 169:0-180:1
    Visibility: public -/
def child_at (c : Children) (i : Std.Usize) : Result Node := do
  match c with
  | Children.Nil => fail panic
  | Children.Cons n rest =>
    if i = 0#usize
    then ok n
    else let i1 ← i - 1#usize
         child_at rest i1
partial_fixpoint

/-- [btree_kernel::replace_child]:
    Source: 'src/lib.rs', lines 184:0-195:1 -/
def replace_child
  (c : Children) (pos : Std.Usize) (x : Node) : Result Children := do
  match c with
  | Children.Nil => ok Children.Nil
  | Children.Cons n rest =>
    if pos = 0#usize
    then let c1 ← clone_children rest
         ok (Children.Cons x c1)
    else
      let n1 ← clone_node n
      let i ← pos - 1#usize
      let c1 ← replace_child rest i x
      ok (Children.Cons n1 c1)
partial_fixpoint

/-- [btree_kernel::replace_and_insert_child]:
    Source: 'src/lib.rs', lines 199:0-213:1 -/
def replace_and_insert_child
  (c : Children) (pos : Std.Usize) (l : Node) (r : Node) :
  Result Children
  := do
  match c with
  | Children.Nil => ok Children.Nil
  | Children.Cons n rest =>
    if pos = 0#usize
    then
      let c1 ← clone_children rest
      ok (Children.Cons l (Children.Cons r c1))
    else
      let n1 ← clone_node n
      let i ← pos - 1#usize
      let c1 ← replace_and_insert_child rest i l r
      ok (Children.Cons n1 c1)
partial_fixpoint

/-- [btree_kernel::children_prefix]:
    Source: 'src/lib.rs', lines 216:0-227:1 -/
def children_prefix (c : Children) (n : Std.Usize) : Result Children := do
  if n = 0#usize
  then ok Children.Nil
  else
    match c with
    | Children.Nil => ok Children.Nil
    | Children.Cons x rest =>
      let n1 ← clone_node x
      let i ← n - 1#usize
      let c1 ← children_prefix rest i
      ok (Children.Cons n1 c1)
partial_fixpoint

/-- [btree_kernel::children_suffix]:
    Source: 'src/lib.rs', lines 230:0-239:1 -/
def children_suffix (c : Children) (n : Std.Usize) : Result Children := do
  if n = 0#usize
  then clone_children c
  else
    match c with
    | Children.Nil => ok Children.Nil
    | Children.Cons _ rest => let i ← n - 1#usize
                              children_suffix rest i
partial_fixpoint

/-- [btree_kernel::get_in_node]:
    Source: 'src/lib.rs', lines 247:0-256:1
    Visibility: public -/
def get_in_node (node : Node) (key : Std.U64) : Result (Option Std.U64) := do
  let (hit, pos) ← find_pos node.entries key
  if hit
  then
    let (_, i) ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Std.U64 ×
        Std.U64)) node.entries pos
    ok (some i)
  else
    let i ← children_len node.children
    if i = 0#usize
    then ok none
    else let n ← child_at node.children pos
         get_in_node n key
partial_fixpoint

/-- [btree_kernel::maybe_split]:
    Source: 'src/lib.rs', lines 260:0-292:1 -/
def maybe_split
  (entries : alloc.vec.Vec (Std.U64 × Std.U64)) (children : Children)
  (replaced : Bool) :
  Result InsertResult
  := do
  let i := alloc.vec.Vec.len entries
  let i1 ← MAX_KEYS
  if i <= i1
  then ok (InsertResult.Fit (Node.mk entries children) replaced)
  else
    let i2 := alloc.vec.Vec.len entries
    let mid ← i2 / 2#usize
    let median ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice (Std.U64 ×
        Std.U64)) entries mid
    let left_entries ← entries_prefix entries mid
    let i3 ← mid + 1#usize
    let right_entries ← entries_suffix entries i3
    let i4 ← children_len children
    let (left_children, right_children) ←
      if i4 = 0#usize
      then ok (Children.Nil, Children.Nil)
      else
        do
        let c ← children_prefix children i3
        let c1 ← children_suffix children i3
        ok (c, c1)
    ok (InsertResult.Split (Node.mk left_entries left_children) median (Node.mk
      right_entries right_children) replaced)

/-- [btree_kernel::insert_into_node]:
    Source: 'src/lib.rs', lines 296:0-327:1
    Visibility: public -/
def insert_into_node
  (node : Node) (key : Std.U64) (val : Std.U64) : Result InsertResult := do
  let (hit, pos) ← find_pos node.entries key
  if hit
  then
    let entries ← replace_entry node.entries pos (key, val)
    let children ← clone_children node.children
    ok (InsertResult.Fit (Node.mk entries children) true)
  else
    let i ← children_len node.children
    if i = 0#usize
    then
      let entries ← insert_entry_at node.entries pos (key, val)
      maybe_split entries Children.Nil false
    else
      let n ← child_at node.children pos
      let ir ← insert_into_node n key val
      match ir with
      | InsertResult.Fit new_child replaced =>
        let children ← replace_child node.children pos new_child
        let entries ←
          alloc.vec.CloneVec.clone (BuiltinClone (Std.U64 × Std.U64))
            node.entries
        ok (InsertResult.Fit (Node.mk entries children) replaced)
      | InsertResult.Split left median right replaced =>
        let entries ← insert_entry_at node.entries pos median
        let children ← replace_and_insert_child node.children pos left right
        maybe_split entries children replaced
partial_fixpoint

/-- [btree_kernel::{btree_kernel::BTree}::new]:
    Source: 'src/lib.rs', lines 331:4-339:5
    Visibility: public -/
def BTree.new : Result BTree := do
  ok
    {
      root := (Node.mk (alloc.vec.Vec.new (Std.U64 × Std.U64)) Children.Nil),
      len := 0#usize
    }

/-- [btree_kernel::{btree_kernel::BTree}::get]:
    Source: 'src/lib.rs', lines 342:4-344:5
    Visibility: public -/
def BTree.get (self : BTree) (key : Std.U64) : Result (Option Std.U64) := do
  get_in_node self.root key

/-- [btree_kernel::{btree_kernel::BTree}::insert]:
    Source: 'src/lib.rs', lines 348:4-377:5
    Visibility: public -/
def BTree.insert
  (self : BTree) (key : Std.U64) (val : Std.U64) : Result BTree := do
  let ir ← insert_into_node self.root key val
  match ir with
  | InsertResult.Fit new_root replaced =>
    if replaced
    then ok { self with root := new_root }
    else
      let new_len ← self.len + 1#usize
      ok { root := new_root, len := new_len }
  | InsertResult.Split left median right replaced =>
    let new_len ← if replaced
                    then ok self.len
                    else self.len + 1#usize
    let entries ←
      alloc.vec.Vec.push (alloc.vec.Vec.new (Std.U64 × Std.U64)) median
    ok
      {
        root :=
          (Node.mk
            entries
            (Children.Cons
            left
            (Children.Cons
            right
            Children.Nil))),
        len := new_len
      }

end btree_kernel
