-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [key_kernel]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace key_kernel

/-- [key_kernel::encode_u64]: loop body 0:
    Source: 'src/lib.rs', lines 27:4-31:5
    Visibility: public -/
@[rust_loop_body]
def encode_u64_loop.body
  (v : Std.U64) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  if i < 8#usize
  then
    let i1 ← 7#usize - i
    let shift ← 8#usize * i1
    let i2 ← v >>> shift
    let i3 ← lift (i2 &&& 255#u64)
    let i4 ← lift (UScalar.cast .U8 i3)
    let out1 ← alloc.vec.Vec.push out i4
    let i5 ← i + 1#usize
    ok (cont (out1, i5))
  else ok (done out)

/-- [key_kernel::encode_u64]: loop 0:
    Source: 'src/lib.rs', lines 27:4-31:5
    Visibility: public -/
@[rust_loop]
def encode_u64_loop
  (v : Std.U64) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => encode_u64_loop.body v out1 i1)
    (out, i)

/-- [key_kernel::encode_u64]:
    Source: 'src/lib.rs', lines 24:0-33:1
    Visibility: public -/
@[reducible]
def encode_u64 (v : Std.U64) : Result (alloc.vec.Vec Std.U8) := do
  encode_u64_loop v (alloc.vec.Vec.new Std.U8) 0#usize

/-- [key_kernel::decode_u64]: loop body 0:
    Source: 'src/lib.rs', lines 41:4-44:5
    Visibility: public -/
@[rust_loop_body]
def decode_u64_loop.body
  (b : Slice Std.U8) (acc : Std.U64) (i : Std.Usize) :
  Result (ControlFlow (Std.U64 × Std.Usize) Std.U64)
  := do
  if i < 8#usize
  then
    let i1 ← acc <<< 8#i32
    let i2 ← Slice.index_usize b i
    let i3 ← lift (UScalar.cast .U64 i2)
    let acc1 ← lift (i1 ||| i3)
    let i4 ← i + 1#usize
    ok (cont (acc1, i4))
  else ok (done acc)

/-- [key_kernel::decode_u64]: loop 0:
    Source: 'src/lib.rs', lines 41:4-44:5
    Visibility: public -/
@[rust_loop]
def decode_u64_loop
  (b : Slice Std.U8) (acc : Std.U64) (i : Std.Usize) : Result Std.U64 := do
  loop
    (fun (acc1, i1) => decode_u64_loop.body b acc1 i1)
    (acc, i)

/-- [key_kernel::decode_u64]:
    Source: 'src/lib.rs', lines 35:0-46:1
    Visibility: public -/
def decode_u64 (b : Slice Std.U8) : Result (Option Std.U64) := do
  let i := Slice.len b
  if i != 8#usize
  then ok none
  else let acc ← decode_u64_loop b 0#u64 0#usize
       ok (some acc)

/-- [key_kernel::encode_i64]:
    Source: 'src/lib.rs', lines 50:0-52:1
    Visibility: public -/
def encode_i64 (v : Std.I64) : Result (alloc.vec.Vec Std.U8) := do
  let i ← lift (IScalar.hcast .U64 v)
  let i1 ← 1#u64 <<< 63#i32
  let i2 ← lift (i ^^^ i1)
  encode_u64 i2

/-- [key_kernel::decode_i64]:
    Source: 'src/lib.rs', lines 54:0-59:1
    Visibility: public -/
def decode_i64 (b : Slice Std.U8) : Result (Option Std.I64) := do
  let o ← decode_u64 b
  match o with
  | none => ok none
  | some biased =>
    let i ← 1#u64 <<< 63#i32
    let i1 ← lift (biased ^^^ i)
    let i2 ← lift (UScalar.hcast .I64 i1)
    ok (some i2)

/-- [key_kernel::ESCAPE]
    Source: 'src/lib.rs', lines 61:0-61:28
    Visibility: public -/
@[global_simps, irreducible] def ESCAPE : Std.U8 := 255#u8

/-- [key_kernel::TERMINATOR]
    Source: 'src/lib.rs', lines 62:0-62:32
    Visibility: public -/
@[global_simps, irreducible] def TERMINATOR : Std.U8 := 1#u8

/-- [key_kernel::escape_and_terminate]: loop body 0:
    Source: 'src/lib.rs', lines 68:4-77:5
    Visibility: public -/
@[rust_loop_body]
def escape_and_terminate_loop.body
  (bytes : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    let b ← Slice.index_usize bytes i
    let out1 ←
      if b = 0#u8
      then
        do
        let out2 ← alloc.vec.Vec.push out 0#u8
        alloc.vec.Vec.push out2 ESCAPE
      else alloc.vec.Vec.push out b
    let i2 ← i + 1#usize
    ok (cont (out1, i2))
  else ok (done out)

/-- [key_kernel::escape_and_terminate]: loop 0:
    Source: 'src/lib.rs', lines 68:4-77:5
    Visibility: public -/
@[rust_loop]
def escape_and_terminate_loop
  (bytes : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => escape_and_terminate_loop.body bytes out1 i1)
    (out, i)

/-- [key_kernel::escape_and_terminate]:
    Source: 'src/lib.rs', lines 65:0-81:1
    Visibility: public -/
def escape_and_terminate
  (bytes : Slice Std.U8) : Result (alloc.vec.Vec Std.U8) := do
  let out ←
    escape_and_terminate_loop bytes (alloc.vec.Vec.new Std.U8) 0#usize
  let out1 ← alloc.vec.Vec.push out 0#u8
  alloc.vec.Vec.push out1 TERMINATOR

/-- [key_kernel::unescape_until_terminator]: loop body 0:
    Source: 'src/lib.rs', lines 1:0-111:5
    Visibility: public -/
@[rust_loop_body]
def unescape_until_terminator_loop.body
  (bytes : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize)
  (done1 : Bool) (bad : Bool) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize × Bool × Bool)
    ((alloc.vec.Vec Std.U8) × Std.Usize × Bool))
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    if done1
    then ok (done (out, i, true))
    else
      if bad
      then ok (done (out, i, false))
      else
        let b ← Slice.index_usize bytes i
        if b = 0#u8
        then
          let i2 ← i + 1#usize
          let i3 := Slice.len bytes
          if i2 >= i3
          then ok (cont (out, i, false, true))
          else
            let next ← Slice.index_usize bytes i2
            if next = TERMINATOR
            then let i4 ← i + 2#usize
                 ok (cont (out, i4, true, false))
            else
              if next = ESCAPE
              then
                let out1 ← alloc.vec.Vec.push out 0#u8
                let i4 ← i + 2#usize
                ok (cont (out1, i4, false, false))
              else ok (cont (out, i, false, true))
        else
          let out1 ← alloc.vec.Vec.push out b
          let i2 ← i + 1#usize
          ok (cont (out1, i2, false, false))
  else ok (done (out, i, done1))

/-- [key_kernel::unescape_until_terminator]: loop 0:
    Source: 'src/lib.rs', lines 1:0-111:5
    Visibility: public -/
@[rust_loop]
def unescape_until_terminator_loop
  (bytes : Slice Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize)
  (done1 : Bool) (bad : Bool) :
  Result ((alloc.vec.Vec Std.U8) × Std.Usize × Bool)
  := do
  loop
    (fun (out1, i1, done2, bad1) => unescape_until_terminator_loop.body bytes
      out1 i1 done2 bad1)
    (out, i, done1, bad)

/-- [key_kernel::unescape_until_terminator]:
    Source: 'src/lib.rs', lines 85:0-113:1
    Visibility: public -/
def unescape_until_terminator
  (bytes : Slice Std.U8) (at1 : Std.Usize) :
  Result (Option ((alloc.vec.Vec Std.U8) × Std.Usize))
  := do
  let (out, i, done1) ←
    unescape_until_terminator_loop bytes (alloc.vec.Vec.new Std.U8) at1 false
      false
  if done1
  then ok (some (out, i))
  else ok none

/-- [key_kernel::encode_bytes]:
    Source: 'src/lib.rs', lines 115:0-117:1
    Visibility: public -/
def encode_bytes (b : Slice Std.U8) : Result (alloc.vec.Vec Std.U8) := do
  alloc.slice.Slice.to_vec core.clone.CloneU8 b

/-- [key_kernel::decode_bytes]:
    Source: 'src/lib.rs', lines 119:0-121:1
    Visibility: public -/
def decode_bytes
  (b : Slice Std.U8) : Result (Option (alloc.vec.Vec Std.U8)) := do
  let v ← alloc.slice.Slice.to_vec core.clone.CloneU8 b
  ok (some v)

/-- [key_kernel::encode_pair_bytes_u64]: loop body 0:
    Source: 'src/lib.rs', lines 129:4-132:5
    Visibility: public -/
@[rust_loop_body]
def encode_pair_bytes_u64_loop.body
  (tail : alloc.vec.Vec Std.U8) (out : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i1 := alloc.vec.Vec.len tail
  if i < i1
  then
    let i2 ←
      alloc.vec.Vec.index (core.slice.index.SliceIndexUsizeSlice Std.U8) tail i
    let out1 ← alloc.vec.Vec.push out i2
    let i3 ← i + 1#usize
    ok (cont (out1, i3))
  else ok (done out)

/-- [key_kernel::encode_pair_bytes_u64]: loop 0:
    Source: 'src/lib.rs', lines 129:4-132:5
    Visibility: public -/
@[rust_loop]
def encode_pair_bytes_u64_loop
  (out : alloc.vec.Vec Std.U8) (tail : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (out1, i1) => encode_pair_bytes_u64_loop.body tail out1 i1)
    (out, i)

/-- [key_kernel::encode_pair_bytes_u64]:
    Source: 'src/lib.rs', lines 125:0-134:1
    Visibility: public -/
def encode_pair_bytes_u64
  (a : Slice Std.U8) (b : Std.U64) : Result (alloc.vec.Vec Std.U8) := do
  let out ← escape_and_terminate a
  let tail ← encode_u64 b
  encode_pair_bytes_u64_loop out tail 0#usize

/-- [key_kernel::decode_pair_bytes_u64]: loop body 0:
    Source: 'src/lib.rs', lines 142:12-145:13
    Visibility: public -/
@[rust_loop_body]
def decode_pair_bytes_u64_loop.body
  (bytes : Slice Std.U8) (tail : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (ControlFlow ((alloc.vec.Vec Std.U8) × Std.Usize) (alloc.vec.Vec
    Std.U8))
  := do
  let i1 := Slice.len bytes
  if i < i1
  then
    let i2 ← Slice.index_usize bytes i
    let tail1 ← alloc.vec.Vec.push tail i2
    let i3 ← i + 1#usize
    ok (cont (tail1, i3))
  else ok (done tail)

/-- [key_kernel::decode_pair_bytes_u64]: loop 0:
    Source: 'src/lib.rs', lines 142:12-145:13
    Visibility: public -/
@[rust_loop]
def decode_pair_bytes_u64_loop
  (bytes : Slice Std.U8) (tail : alloc.vec.Vec Std.U8) (i : Std.Usize) :
  Result (alloc.vec.Vec Std.U8)
  := do
  loop
    (fun (tail1, i1) => decode_pair_bytes_u64_loop.body bytes tail1 i1)
    (tail, i)

/-- [key_kernel::decode_pair_bytes_u64]:
    Source: 'src/lib.rs', lines 136:0-152:1
    Visibility: public -/
def decode_pair_bytes_u64
  (bytes : Slice Std.U8) :
  Result (Option ((alloc.vec.Vec Std.U8) × Std.U64))
  := do
  let o ← unescape_until_terminator bytes 0#usize
  match o with
  | none => ok none
  | some p =>
    let (head, at1) := p
    let tail ←
      decode_pair_bytes_u64_loop bytes (alloc.vec.Vec.new Std.U8) at1
    let s := alloc.vec.Vec.deref tail
    let o1 ← decode_u64 s
    match o1 with
    | none => ok none
    | some v => ok (some (head, v))

end key_kernel
